### ISSUE TITLE
Not able to run imMens

### ISSUE THREAD

**Issue by anupamme** [uwdata/imMens#1]
1. Is the code complete (in the sense one can download and run it)?
2. Can you put little instructions on how to run (I could not find index.html).

**Comment by umaar** [comment]
Nice project @zcliu - any chance you could add the Jar file to tile-compute and/or instructions on how to compile it ourselves (which might be better)? Thanks!

**Comment by zcliu** [comment]
@umaar Thanks for asking. We are working on supporting tile-compute for users' own datasets now. This requires some major work on the backend. Currently it's still work in progress.
